### PR TITLE
[executor] control flow

### PR DESCRIPTION
**Pull request by liketechnik**

### CODE REVIEW

**Comment by liketechnik** [comment]
Still TODO: fcmp, dcmp and similiar

**Comment by liketechnik** [comment]
also missing: test files

**Comment by JonaZz747** [comment]
@liketechnik you may add the missing test files now

**Review by realJule — APPROVED** [review]

**Review by JonaZz747 — APPROVED** [review]
Does the test case cover float and double nan?

**Comment by liketechnik** [comment]
Ours not, I'm not sure about the Compiler group's one.

**Pull request merged**
