### PR TITLE
Branch offsets by opcodes and wide opcode

### LINKED ISSUE #61: [classloader] goto/jump: parse offset into opcode count
Follow up of #60

### PR DESCRIPTION
**Pull request by Kerreytsugo**
closes #61

### CODE REVIEW

**Review by liketechnik — APPROVED** [review]

**Comment by liketechnik** [comment]
You might want to rebase this to make sure this doesn't break on main after the test changes in #65

**Review by realJule — APPROVED** [review]

**Review by JonaZz747 — CHANGES_REQUESTED** [review]
`opcode_sized` is a list storing the size of the parsed opcodes, important for offset calc

The size of an opcode depends on the opcode per se, so an opcode "instance" always has the size of an opcode, correct?

Would it be wiser (if above assumption true) to therefore store the size of the opcode directly in the opcode as final opcode attribute? Is this possible for rust enums?

**Comment by liketechnik** [comment]
> so an opcode "instance" always has the size of an opcode, correct?

No. E.g. the `wide` OpCode modifies how the OpCode directly following it is parsed, i.e., an OpCode behind a `wide` needs more space than without `wide`. Our OpCode enum (intentionally) ignores these differences, but therefore cannot accurately represent the size the OpCode originally had in the bytecode.

>  Is this possible for rust enums?

No. In general, there are two possibilites:

a) implement a method `byte_size` (or similiar) for the `OpCode` enum with signature `fn byte_size(&self) -> usize` that returns the size in bytes of an OpCode instance. This is impossible for the reason discussed above.
b) Create a struct around the enum (or use a tuple) that contains the enum and information that is indepent of the OpCode variant (like size in our case). This is unnecessary imho, since we discard this information right away anyway, and we do not win anything by keeping size and OpCode in the same Vec: the code reconstructing the Jump/Goto instructions uses indices anyway.

**Comment by JonaZz747** [comment]
Understand.

I thought, the size of an opcode is a feature of an opcode and therefore should be handled directly in the opcode and not outside. 

But - because opcode sizes can change and we unite some opcodes (`const_*`) &rarr; this is harder to implement in our code, also opcode size is only required for classloader and not later for vm &rrarr; just keep it as is.

**Pull request merged**
